apiVersion: v1
kind: ConfigMap
metadata:
  name: yurt-tunnel-server-cfg
  namespace: kube-system
data:
  localhost-proxy-ports: "10255, 10250, 10266, 10267"
  http-proxy-ports: "9445"
  https-proxy-ports: "9100"